name: Scrape Swamp Stats

on:
  schedule:
    - cron: '0 */6 * * *'  # every hour
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: bundle install

      - name: Run scraper
        run: ruby scraper.rb

      - name: Commit output and Gemfile.lock
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add output/swamp_stats.json Gemfile.lock
          git commit -m "Update swamp stats and Gemfile.lock"
          git push
